/* This file was generated by generate_AVR_asm.py in the Assembler folder in the project root. 
   If you wish to change the assembly code defined in here, modify the 6502avr.s file and run  
   the python3.5 script. It will automatically override this file if compilation is successful.*/


.EQU RAM_SIZE = 1024

.CSEG
RAMcodeUNLOADED:
.DB 0xea,0xea,0xea,0xea,0x4c,0x00,0x00

ROMcode:
.DB 0xea,0xea,0xea,0xea,0x4c,0x00,0x08

.DSEG
RAMcode: .BYTE RAM_SIZE

.ESEG
EEPROMcode:
.DB 0xea,0xea,0xea,0xea,0x4c,0x00,0x10

.CSEG
